In [2]:
import pandas as pd
import numpy as np

print("Pandas version:", pd.__version__)

Pandas version: 2.2.3

In [3]:
from google.colab import files
uploaded = files.upload()

Saving heart.csv to heart (1).csv

In [4]:
df = pd.read_csv("heart.csv")
print("Dataset loaded successfully!")

Dataset loaded successfully!

In [5]:
print("First Five Row:")
df.head()

First Five Row:

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,52,1,0,125,212,0,1,168,0,1.0,2,2,3,0
1,53,1,0,140,203,1,0,155,1,3.1,0,0,3,0
2,70,1,0,145,174,0,1,125,1,2.6,0,0,3,0
3,61,1,0,148,203,0,1,161,0,0.0,2,1,3,0
4,62,0,0,138,294,1,1,106,0,1.9,1,3,2,0

In [6]:
print("last five row")
df.tail()

last five row

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
1020,59,1,1,140,221,0,1,164,1,0.0,2,0,2,1
1021,60,1,0,125,258,0,0,141,1,2.8,1,1,3,0
1022,47,1,0,110,275,0,0,118,1,1.0,1,1,2,0
1023,50,0,0,110,254,0,0,159,0,0.0,2,0,2,1
1024,54,1,0,120,188,0,1,113,0,1.4,1,1,3,0

In [7]:
print("Dataset shape (rows, columns):", df.shape)
print(f"Total row {df.shape[0]}  and total columns {df.shape[1]} ")

Dataset shape (rows, columns): (1025, 14)
Total row 1025  and total columns 14

In [8]:
print("Every column name:")
print(df.columns.tolist())

Every column name:
['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach', 'exang', 'oldpeak', 'slope', 'ca', 'thal', 'target']

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1025 entries, 0 to 1024
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       1025 non-null   int64
 1   sex       1025 non-null   int64
 2   cp        1025 non-null   int64
 3   trestbps  1025 non-null   int64
 4   chol      1025 non-null   int64
 5   fbs       1025 non-null   int64
 6   restecg   1025 non-null   int64
 7   thalach   1025 non-null   int64
 8   exang     1025 non-null   int64
 9   oldpeak   1025 non-null   float64
 10  slope     1025 non-null   int64
 11  ca        1025 non-null   int64
 12  thal      1025 non-null   int64
 13  target    1025 non-null   int64
dtypes: float64(1), int64(13)
memory usage: 112.2 KB

In [10]:
print("column missing value:")
print(df.isnull().sum())

column missing value:
age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [11]:
print("Heart disease  patient")
print(df['target'].value_counts())
print()
print("(1 = heart disease positive, 0 = heart disease negative")

Heart disease  patient
target
1    526
0    499
Name: count, dtype: int64

(1 = heart disease positive, 0 = heart disease negative

In [12]:
print(df['sex'].value_counts())
print()
print("(1 = Male, 0 = Female)")

sex
1    713
0    312
Name: count, dtype: int64

(1 = Male, 0 = Female)

In [13]:
print("First 10 row:")
df.iloc[0:10]

First 10 row:

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,52,1,0,125,212,0,1,168,0,1.0,2,2,3,0
1,53,1,0,140,203,1,0,155,1,3.1,0,0,3,0
2,70,1,0,145,174,0,1,125,1,2.6,0,0,3,0
3,61,1,0,148,203,0,1,161,0,0.0,2,1,3,0
4,62,0,0,138,294,1,1,106,0,1.9,1,3,2,0
5,58,0,0,100,248,0,0,122,0,1.0,1,0,2,1
6,58,1,0,114,318,0,2,140,0,4.4,0,3,1,0
7,55,1,0,160,289,0,0,145,1,0.8,1,1,3,0
8,46,1,0,120,249,0,0,144,0,0.8,2,0,3,0
9,54,1,0,122,286,0,0,116,1,3.2,1,2,2,0

In [14]:
print("Column positions:")
for i, col in enumerate(df.columns):
    print(f"{i}: {col}")

Column positions:
0: age
1: sex
2: cp
3: trestbps
4: chol
5: fbs
6: restecg
7: thalach
8: exang
9: oldpeak
10: slope
11: ca
12: thal
13: target

In [15]:
selected_cols = df.iloc[:, [0, 1, 4]]
print("age, sex, cholesterol column :")
selected_cols.head()

age, sex, cholesterol column :

   age  sex  chol
0   52    1   212
1   53    1   203
2   70    1   174
3   61    1   203
4   62    0   294

In [16]:
subset = df.iloc[20:31, 0:5]
print("Row 20-30, Column 0-4:")
subset

Row 20-30, Column 0-4:

    age  sex  cp  trestbps  chol
20   60    1   2       140   185
21   67    0   0       106   223
22   45    1   0       104   208
23   63    0   2       135   252
24   42    0   2       120   209
25   61    0   0       145   307
26   44    1   2       130   233
27   58    0   1       136   319
28   56    1   2       130   256
29   55    0   0       180   327
30   44    1   0       120   169

In [17]:
older_than_50 = df[df['age'] > 50]
print("Older than 50 years:", older_than_50.shape[0])
older_than_50.head()

Older than 50 years: 710

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,52,1,0,125,212,0,1,168,0,1.0,2,2,3,0
1,53,1,0,140,203,1,0,155,1,3.1,0,0,3,0
2,70,1,0,145,174,0,1,125,1,2.6,0,0,3,0
3,61,1,0,148,203,0,1,161,0,0.0,2,1,3,0
4,62,0,0,138,294,1,1,106,0,1.9,1,3,2,0

In [18]:
disease_high_chol = df[(df['target'] == 1) & (df['chol'] > 240)]
print("Heart disease + cholesterol > 240 type patient:")
disease_high_chol.head()

Heart disease + cholesterol > 240 type patient:

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
5,58,0,0,100,248,0,0,122,0,1.0,1,0,2,1
16,51,0,2,140,308,0,0,142,0,1.5,2,1,2,1
18,50,0,1,120,244,0,1,162,0,1.1,2,0,2,1
23,63,0,2,135,252,0,0,172,0,0.0,2,0,2,1
31,50,0,1,120,244,0,1,162,0,1.1,2,0,2,1

In [20]:
count = disease_high_chol.shape[0]
print(count)

222